### ISSUE TITLE
LIB_JModuleHelperDefault fatal error on J 3.2.1

### ISSUE THREAD

**Issue by cbahiana** [juliopontes/joomla-override#11]
The plugin is already being used on a Joomla 3.1.5 site. When upgraded to Joomla 3.2.1 comes the white screen of death. The Apache error log shows a fatal error:

"Class 'LIB_JModuleHelperDefault' not found" apontando para "plugins/system/joomlaoverride/core/module/helper.php on line 13"

Disabling the plugin on the database makes the site work again.

**Comment by juliopontes** [comment]
Solved, I'll update code asap.

**Comment by cbahiana** [comment]
Thank you Julio
