### ISSUE TITLE
Cannot reference $this

### ISSUE THREAD

**Issue by haydenyoung** [juliopontes/joomla-override#12]
Seeing the above error in latest master due to $this being referenced outside an instantiated class (around line 27 in joomlaoverride.php).

Loaded the plugin params via the jpluginhelper class instead which rectified the problem:

$plugin = JPluginHelper::getPlugin('system', 'joomlaoverride');
$pluginParams = new JRegistry($plugin->params);
$customPath = JPath::clean($pluginParams->get('global_path','override'));

Cheers

Hayden

**Comment by juliopontes** [comment]
fixed

**Comment by haydenyoung** [comment]
Addressed in commit 86bb19c3aa76103a715ed0cb4a700d2ae1ff08c5
