### ISSUE TITLE
Cannot use non-default template for any menu item

### ISSUE THREAD

**Issue by haydenyoung** [juliopontes/joomla-override#13]
To reproduce:
- Fresh install of Joomla 3.2.1
- Default site template set to protostar
- Create a home menu item (if not already available)
- Open Beez3 and assign home menu item to this template (using Template's Menu Assignment)

View the site home page. Beez3 loads instead of default protostar (correct outcome).

Install Joomla Override master code from this repository and enable plugin.

Reload home page. Default protostar template is loaded instead of Beez3 (incorrect outcome).

Disable Joomla Override from plugin manager. Refresh home page. Beez3 will load correctly again.

This issue occurs for other menu items as well; a category blog menu item assigned to Beez3 will load protostar when Joomla Override is enabled.

Changing the load order of system plugins does nothing (moved to first then last but still the default template was loaded).

Cheers

Hayden

**Comment by haydenyoung** [comment]
I've isolated this issue further. It seems that the call to getTemplate on line 22 in joomlaoverride.php causes the default template to be loaded (I'm guessing all system plugins are processed BEFORE the template's index.php is called, thus causing the wrong template to be loaded).

I'm assuming that moving the logic at the beginning of the joomlaoverride plugin class (I.e. all code before PlgSystemJoomlaOverride) into the declared event would fix the problem.

Cheers

Hayden

**Comment by juliopontes** [comment]
Updated plugin, please check.

**Comment by haydenyoung** [comment]
Looks like the menu-specific template is still not available during __construct(). Testing results in the default template still being referenced instead of the menu specific template (protostar instead of beez3 per the example above).

Cheers

Hayden

**Comment by haydenyoung** [comment]
Addressed in commit 86bb19c3aa76103a715ed0cb4a700d2ae1ff08c5
