### ISSUE TITLE
Fatal error: Cannot redeclare class ContentModelArticles

### ISSUE THREAD

**Issue by likebtn** [juliopontes/joomla-override#18]
Joomla 3.3.1

I am trying to override /components/com_content/models/articles.php

Created /override/com_content/models/articles.php

```
defined('_JEXEC') or die;

class ContentModelArticles extends ContentModelArticlesDefault
{
    protected function getListQuery()
    {
        return parent::getListQuery();
    }
}
```

Created "Featured Articles" menu item.

Receiving the following error:
<strong>Fatal error: Cannot redeclare class ContentModelArticles in /components/com_content/models/articles.php on line 680</strong>

**Comment by juliopontes** [comment]
Check if this file are loaded. Ex.: put a die(**FILE**); and see on frontend.

**Comment by likebtn** [comment]
Yes. Both files
/override/com_content/models/articles.php
/components/com_content/models/articles.php

are loaded.

**Comment by likebtn** [comment]
It worked for ContentModelCategory:

class ContentModelCategory extends ContentModelCategoryDefault
