### ISSUE TITLE
Conflict with Advanced Module Manager

### ISSUE THREAD

**Issue by jwhelan72** [juliopontes/joomla-override#3]
The plugin breaks when AMM by NoNumber is installed.  I believe that this is due to your recent additions of module overrides.  I'd like to try the earlier version that did not provide for module overrides.  Perhaps you'd be kind enough to repost that one?

Regards,

John Whelan

**Comment by juliopontes** [comment]
Thanks for report issue, I"ll check how to fix it.

**Comment by jwhelan72** [comment]
Any chance you could post your earlier version that did not include overrides for modules?  I could really use it.

**Comment by jwhelan72** [comment]
Julio,

Did you ever get a chance to look at this?  Or, perhaps a suggestion on how to remove the modules overrides feature?  I could really use it.

**Comment by juliopontes** [comment]
What version of joomla are you using? Give me all specs for simulate here and try to solve.

**Comment by juliopontes** [comment]
Think have fixed please check with new plugin code at github
