### ISSUE TITLE
Module Class Suffix bug

### ISSUE THREAD

**Issue by marcanuy** [juliopontes/joomla-override#6]
Hi, In Joomla 3.0.2 Stable with Protostart template, Module Style "html5", Module tag "div", It generates module classes without "moduletable" prefix. For modules located in "right" position (position-7) It is always adding the "well" BS class too. For modules located in "breadcrumbs" position (position-2) no div is rendered.
Best regards

**Comment by juliopontes** [comment]
What I need to do, for simulate this error?
