### ISSUE TITLE
Not overriding component main file

### ISSUE THREAD

**Issue by Mediage** [juliopontes/joomla-override#9]
Hi,

I am trying to set up overrides on the Media Manager component. 
I have done the following:
- Install and enable latest Github version of plugin
- Created folder override/com_media
- Changed the plugin params to match the Global Override folder (e.g.: override)
- Placed a modified version of media.php in the override/com_media folder

Somehow my changes are not visible in the site itself. When I put the changes in the original media.php file, it works fine. 

I used to work with the JED version of the plugin, Plugin Override (http://extensions.joomla.org/extensions/style-a-design/templating/15611) , and that didn't seem to work either.

Oh, little detail: I am aware that I am changing the front-end version of com_media. :-)

Any suggestions?

Apart from that: fantastic plugin that should be part of the Joomla core! Big time-saver when updating customized components/modules!

**Comment by juliopontes** [comment]
Try this: override/administrator/com_media/media.php

**Comment by Mediage** [comment]
Thanks for your reply! Unfortunately that doesn't work. It doesn't get changed either in the front or backend.

**Comment by juliopontes** [comment]
will test here and feedback you

**Comment by Mediage** [comment]
Any results so far?

Thanks!

**Comment by juliopontes** [comment]
added support for entry point. (main file) Update code asap.
